server:
    port: 8088

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://8.134.168.60:3306/shiro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&&useSSL=true
        connectionTimeout: 100000
        username: root
        password: shu@123
        type: com.alibaba.druid.pool.DruidDataSource
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    redis:
        host: 8.134.168.60
        port: 6379
        jedis:
            pool:
                max-idle: 8
                min-idle: 0
                max-active: 8
                max-wait: -1
        password: shu@123
        timeout: 10000
        database: 0
#shiro:
#    unauthorized:
#        url: http://localhost:5003/index.html

# mybatis-plus\u76F8\u5173\u914D\u7F6E
mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        #\u4E00\u822C\u6211\u4EEC\u4F1A\u505A3\u4E2A\u914D\u7F6E,\u5176\u4F59\u9ED8\u8BA4\u5373\u53EF
        #    freemarker:
        #        #\u66B4\u9732session\u5BF9\u8C61\u7684\u5C5E\u6027
        #        expose-session-attributes: true
        #        suffix: .ftl
        #        #\u914D\u7F6E\u4E3A\u4F20\u7EDF\u6A21\u5F0F\uFF0C\u7A7A\u503C\u81EA\u52A8\u5904\u7406
        #        settings:
        #            classic_compatible: true
        #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
        #spring.datasource.url=jdbc:mysql://8.134.168.60:3306/proj_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&&useSSL=true
        #spring.datasource.connectionTimeout= 100000
        #spring.datasource.username=root
        #spring.datasource.password=shu@123
        #spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

